version: '3'

services:
    gatsby:
        container_name: gatsby
        restart: always
        build: .
        ports:
            - '8000:8000'
        volumes:
            - ./:/opt/app
            - /opt/app/node_modules
